### ISSUE TITLE
Error onMessageReceived from whatsapp.

### ISSUE THREAD

**Issue by ReaLcl** [stenyak/breakbot#19]
When I send a message from my whatsapp number to the whatsapp-bot phone number I get the following error:

Traceback (most recent call last):
  File "/home/real/botw/catch_them_all.py", line 10, in wrapper
    return function(_args, *_kwargs)
TypeError: onMessageReceived() takes exactly 7 arguments (8 given)

2014-04-14 17:33:19.354927 EE catch_them_all.py:12: Exception in function onMessageReceived
2014-04-14 17:33:48.581702 EE catch_them_all.py:12:
Traceback (most recent call last):
  File "/home/real/botw/catch_them_all.py", line 10, in wrapper
    return function(_args, *_kwargs)
TypeError: onMessageReceived() takes exactly 7 arguments (8 given)

2014-04-14 17:33:48.581702 EE catch_them_all.py:12: Exception in function onMessageReceived

**Comment by stenyak** [comment]
It looks like private messaging was a bit broken, but after today's commits, this should be working without problems. Please test it after updating your code, and let me know if there's any further problems.

**Comment by TonyStark** [comment]
```
ul said to None: <Rutul> Test message
2014-07-28 15:04:07.438702 EE catch_them_all.py:12: 
Traceback (most recent call last):
  File "/home/mac/Downloads/breakbot/catch_them_all.py", line 10, in wrapper
    return function(*args, **kwargs)
  File "bot.py", line 78, in irc_msg_received
    raise Exception("Target not specified. Please prefix you private messages with a nickname (e.g. 'person1: hello') or phone number (e.g. '+34555555373: hello')")
```

I get above error after message received
