### ISSUE TITLE
Since today: wa_bot.py:138: Auth Failed: invalid

### ISSUE THREAD

**Issue by h1rule** [stenyak/breakbot#27]
Hello,

since today, all my related breakbot Bots response:

wa_bot.py:138: Auth Failed: invalid

Also: I registered a fresh new Number with WhatsApp, but Auth Failed, invalid still replys.
Looks like Mark Zuckerburg updated something!

**Comment by Hugo2607** [comment]
The bot's still able to log in just fine over here, so it's probably not like WhatsApp updated their authentication infrastructure.

BTW, does your breakbot also drop all messages with non-ASCII characters (emoji's for example) in them?

**Comment by h1rule** [comment]
My Bot drops everything with ":"

:(

**Comment by stenyak** [comment]
@Hugo2607 emoji problem here: #26
@capsload ":" problem here: #24
Please do _not_ mix issues.

@Hugo2607 auth problem maybe due to expired whatsapp account. try to use the account with the regular whataspp software, check if it complains about it, and pay the euro it asks for if that's the problem. please report back with what you find. thanks!

**Comment by thinko** [comment]
I have the same problem, the account expired (it's first year ran out) and I renewed it (used 3rd-party renewal link), it worked for a few days and then it died, doing the exact same thing as happened to capsload:

2014-09-12 21:26:01.941127 II irc_bot.py:160:  ->- IRC #chan: <User1> Game on!
2014-09-12 21:26:01.965967 II irc_bot.py:146:  >>> IRC PRIVMSG #chan :<User1> Game on!
2014-09-12 23:12:22.226894 II wa_bot.py:142: Disconnected WA client (15084889056): closed
2014-09-12 23:12:23.040911 II wa_bot.py:138: Auth Failed: invalid
2014-09-12 23:12:25.872694 II wa_bot.py:138: Auth Failed: invalid

It was rather strange that in addition to getting disconnected and failing auth, it actually disappeared from our whatsapp clients, the contact with the bot phone number doesn't show as being a whatsapp user, and when it disappeared it actually appeared to the users in whatsapp as: "Ircbot was removed". 
![image](https://cloud.githubusercontent.com/assets/1501398/4484418/578e2834-49bb-11e4-9c0f-5ab8b46d1ddc.png)
I don't understand how after paying for the renewal legitimately, it gets killed? Very suspicious, but at worst I want my dollar back from Mark Z.

**Comment by stenyak** [comment]
That message definitely points to the bot number being possibly banned.

A quick search on the net yields similar reports from other bot users (not necessarily breakbot users)... but it doesn't seem widespread. FWIW my bot is still running after 20 months and one account renewal.

I think there's not much I can do on this front, since I have no idea how Whatsapp determines which numbers to ban and which not. It could be a special secret API (special responses from the servers that in turn require specific replies, and go unnoticed by yowsup, for example), or maybe inspection of actual messages to detect spammers (in case the account is being used for that)... Who knows.

**Comment by marcohald** [comment]
I got the error wa_bot.py:138: Auth Failed: invalid with a fresh install i made today.
/get_libs.sh

> ./get_libs.sh
> A    oyoyo/parse.py
> A    oyoyo/client.py
> A    oyoyo/**init**.py
> A    oyoyo/examplebot.py
> A    oyoyo/cmdhandler.py
> A    oyoyo/ircevents.py
> A    oyoyo/helpers.py
> Checked out revision 55.
> Submodule 'yowsup.git' (git@github.com:stenyak/yowsup.git) registered for path 'yowsup.git'
> Cloning into 'yowsup.git'...
> remote: Counting objects: 859, done.
> remote: Compressing objects: 100% (342/342), done.
> remote: Total 859 (delta 510), reused 859 (delta 510)
> Receiving objects: 100% (859/859), 183.68 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (510/510), done.
> Checking connectivity... done.
> Submodule path 'yowsup.git': checked out '6b83dad5506acbd9691853a4e73f587be695b38b'
> python bot.py
> python bot.py
> 2014-12-07 14:45:39.465282 II bot.py:141: 4 contacts loaded from configuration file
> 2014-12-07 14:45:39.467983 II bot.py:49: Connecting IRC client (my_bot@irc.freenode.net:6667)
> 2014-12-07 14:45:42.666710 II irc_bot.py:122: Joining channels: #sample_room2, #sample_room
> 2014-12-07 14:45:46.611630 II irc_bot.py:140: Connected IRC client (my_bot@irc.freenode.net:6667)
> 2014-12-07 14:45:46.685385 II bot.py:52: Connecting WA client (49172***4104)
> 2014-12-07 14:45:48.853587 II wa_bot.py:138: Auth Failed: invalid

I had never running breakbot before, so maybe the problem is on my side.
I tried to to test my account with yowsup-cli and it worked without any problem.
Sending messages to one phone number receiveing group messages receiving a normal message.
Have you any suggestions what i can try.
The Number i used was never used with Whatsapp before i did the first registration with yowsup-cli

**Comment by Hugo2607** [comment]
@marcohald I ran into this problem a while ago as well. Basically, Breakbot identifies itself as a Nokia S40 running WhatsApp version 2.12.15. They probably dropped support for this version recently because by changing the version number to 2.12.29 I was able to connect again.

To do this you need to edit /breakbot.git/yowsup.git/src/Yowsup/Common/constants.py and change:

```
    tokenData = {
            "v": "2.12.15",
            "r": "S40-2.12.15",
            "u": "WhatsApp/2.12.15 S40Version/14.26 Device/Nokia302",
            "t": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1391039105258{pho$
            "d": "Nokia302"
    }
```

To this:

```
    tokenData = {
            "v": "2.12.29",
            "r": "S40-2.12.29",
            "u": "WhatsApp/2.12.29 S40Version/14.26 Device/Nokia302",
            "t": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1391039105258{pho$
            "d": "Nokia302"
    }
```

Hope this helps!

**Comment by uppaljs** [comment]
Hi, 

I am facing the same issue , even though I changed the Version numbers , but still had the same issue and the dreaded 2014-12-18 05:43:03.676114 II wa_bot.py:138: Auth Failed: invalid message. Kindly help. My credentials work okay with yowsup-cli latest.

Thanks,

**Comment by clarityworld** [comment]
Same error....as uppaljs

**Comment by Hugo2607** [comment]
Yeah, I got this problem again as well the other day. I fixed it by changing my version number again. It looks like WhatsApp may have banned all the Nokia S40 (the client breakbot pretends to be) clients altogether, but since I don't have an S40 so I'm not sure. You can change the version number to pretty much any phone and version number, but WhatsApp responds to them differently. If you just change the values to the latest Android version, image descriptions are no longer sent as a separate message, and since breakbot hasn't been updated for those, they get dropped altogether. Changing the values to the latest Symbian version seems to work fine though.

I edited "/breakbot.git/yowsup.git/src/Yowsup/Common/constants.py" and changed this:

```
tokenData = {
        "v": "2.12.15",
        "r": "S40-2.12.15",
        "u": "WhatsApp/2.12.15 S40Version/14.26 Device/Nokia302",
        "t": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1391039105258{pho$
        "d": "Nokia302"
}
```

To this:

```
    tokenData = {
            "v": "2.11.860",
            "r": "Nokia-2.11.860",
            "u": "Nokia/2.11.860 Nokia/14.26 Device/Nokia302",
            "t": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1377032097395{pho$
            "d": "Nokia302x"
}
```

If this stops working again, change the version number to the one listed on this page (under the download button):
http://www.whatsapp.com/nokia/

**Comment by clarityworld** [comment]
Hey thanks for help :+1: 
I got this token error now, when i change it to your settings,

root@vps9450:~/breakbot# python bot.py
Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    from wa_bot import WAInterface
  File "/root/breakbot/wa_bot.py", line 10, in <module>
    from Yowsup.connectionmanager import YowsupConnectionManager
  File "/root/breakbot/Yowsup/connectionmanager.py", line 24, in <module>
    from Yowsup.ConnectionIO.connectionengine import ConnectionEngine
  File "/root/breakbot/Yowsup/ConnectionIO/connectionengine.py", line 24, in <module>
    from .bintreenode import BinTreeNodeReader, BinTreeNodeWriter
  File "/root/breakbot/Yowsup/ConnectionIO/bintreenode.py", line 24, in <module>
    from Yowsup.Common.constants import Constants
  File "/root/breakbot/Yowsup/Common/constants.py", line 55
    tokenData = {
    ^
IndentationError: unexpected indent
root@vps9450:~/breakbot#

I think the line should be 
"t": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1377032097395{phone}",

not 

 "t": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1377032097395{pho$

But anyway it still don't work :(

**Comment by Hugo2607** [comment]
Hmmm, looks like you made a mistake in your constants.py. I just saw that I also made a typo in my previous comment, which I just corrected.

Check the spacing around the indentations, and check for any other typo's. If you can't find any, just restore the original constants.py and just change it to the new version numbers without copying the whole thing.

**Comment by clarityworld** [comment]
Question which Token do i have to use? 
The one from my Orginal file, yours or do i somehow have to create my own ? :3

**Comment by Hugo2607** [comment]
Using the same token works fine for me

**Comment by clarityworld** [comment]
Hugo2607 I think i love you !
It works now! 
I'm just wondering how the hell did you figured it out, that you had to change the version in THAT file.

**Comment by Hugo2607** [comment]
No problem man, glad I could help.

When I got the "Auth invalid" error I tried logging into my account on Pidgin using a WhatsApp plugin, didn't work on there either, but the same number did work on my phone, so it couldn't be banned. So I thought the client must be outdated. Turns out the client version is sent in the resource, so I just edited that under the account settings and changed the version number to the latest version, and then I was able to log in. I found the file by opening the Yowsup folder and opening anything that looked like a configuration file in a text editor and looked for the version number.

**Comment by h1rule** [comment]
Trying that Token thing out later today. Hopefully @stenyak finds some time, doing some great updates to breakbot. I love that Bot.

Maybe we can see the encrypted updates soon in breakbot? :P

**Comment by Hugo2607** [comment]
Yeah, changing the version number stopped working for me this Friday. 
I'd check by trying to log into the official client, but I'm not home 
right now so I can't. Did this stop working for anyone else? I hope it's 
not related to WhatsApp banning the users of third party clients (though 
that might have been only been about WhatsApp Plus).

**Comment by h1rule** [comment]
it stops responding after "joining channels.."

**Comment by h1rule** [comment]
I think the whole thing needs to get a update.
After changing the constants.py thing to the nokia token, nothing response after the "joining irc channels..."

:(

**Comment by teknogeek** [comment]
@capsload @Hugo2607 I can confirm that as of today, this is wiorking for me.

In `Yowsup/Common/constants.py`, I changed this:

``` python
tokenData = {
    "v": "2.11.1",
    "r": "S40-2.11.1",
    "u": "WhatsApp/2.11.1 S40Version/14.26 Device/Nokia302",
    "t": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1377032097395{phone}",
    "d": "Nokia302x"
}
```

to this:

``` python
tokenData = {
        "v": "2.11.902",
        "r": "Nokia-2.11.902",
        "u": "Nokia/2.11.902 Nokia/14.26 Device/Nokia302",
        "t": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1377032097395{phone}",
        "d": "Nokia302x"
}
```

**Comment by h1rule** [comment]
Working for me too!
Thank you <3

**Comment by h1rule** [comment]
Not working again.
