### ISSUE TITLE
error on run bot.py

### ISSUE THREAD

**Issue by b0y** [stenyak/breakbot#3]
hey... i want ask. i got error after run bot.py i'm use blackbuntu and run with python 2.6.
this my error.

sniper@sniper-nux~/Desktop/breakbot$ python bot.py
Traceback (most recent call last):
  File "bot.py", line 133, in <module>
    config = json.loads(f.read())
  File "/usr/lib/python2.6/json/**init**.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.6/json/decoder.py", line 336, in raw_decode
    obj, end = self._scanner.iterscan(s, **kw).next()
  File "/usr/lib/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib/python2.6/json/decoder.py", line 183, in JSONObject
    value, end = iterscan(s, idx=end, context=context).next()
  File "/usr/lib/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib/python2.6/json/decoder.py", line 198, in JSONObject
    raise ValueError(errmsg("Expecting property name", s, end - 1))
ValueError: Expecting property name: line 6 column 13 (char 146)

**Comment by stenyak** [comment]
There seems to be a problem while parsing the configuration file.
Judging by the error message, you might need to remove a "," character at the end of line 5th?
But I'm just blindly guessing, I'd need to see your config.json file in order to know for sure.

**Comment by b0y** [comment]
hey...thanks for replay....yes this my wrong... i'm type "," on last contact config. now this can run normally. thanks bro.... :)
